model: fire_fly_gan_base_20240407
sampling_rate: 44100
num_mels: 125
n_fft: 2048
win_size: 2048
hop_size: 512
fmin: 0
fmax: 22050
url: "https://github.com/fishaudio/vocoder/releases/download/1.0.0/firefly-gan-base-generator.ckpt"